[env]
JAVA_HOME = "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
ANDROID_HOME = "{{ env.HOME }}/Library/Android/sdk"
NDK_HOME = "{{ env.HOME }}/Library/Android/sdk/ndk/28.0.13004108"

[tools]
node = "lts"
rust = "stable"
pnpm = "10"
